//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace movies_service.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JediniceMjere
    {
        public JediniceMjere()
        {
            this.Proizvodi = new HashSet<Proizvodi>();
        }
    
        public int JedinicaMjereID { get; set; }
        public string Naziv { get; set; }
    
        public virtual ICollection<Proizvodi> Proizvodi { get; set; }
    }
}
