//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace movies_service.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategorije
    {
        public Kategorije()
        {
            this.ProizvodiKategorijes = new HashSet<ProizvodiKategorije>();
        }
    
        public int KategorijaID { get; set; }
        public string Naziv { get; set; }
    
        public virtual ICollection<ProizvodiKategorije> ProizvodiKategorijes { get; set; }
    }
}
