//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace movies_service.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class moviesEntities : DbContext
    {
        public moviesEntities()
            : base("name=moviesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Glumci> Glumcis { get; set; }
        public DbSet<Kategorije> Kategorijes { get; set; }
        public DbSet<Korisnici> Korisnicis { get; set; }
        public DbSet<Kupci> Kupcis { get; set; }
        public DbSet<Narudzbe> Narudzbes { get; set; }
        public DbSet<Proizvodi> Proizvodis { get; set; }
        public DbSet<ProizvodiGlumci> ProizvodiGlumcis { get; set; }
        public DbSet<ProizvodiKategorije> ProizvodiKategorijes { get; set; }
        public DbSet<Reziseri> Reziseris { get; set; }
        public DbSet<Uloge> Uloges { get; set; }
    }
}
