//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace movies_service.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvodi
    {
        public Proizvodi()
        {
            this.ProizvodiGlumcis = new HashSet<ProizvodiGlumci>();
            this.ProizvodiKategorijes = new HashSet<ProizvodiKategorije>();
        }
    
        public int ProizvodID { get; set; }
        public string Naziv { get; set; }
        public string Sifra { get; set; }
        public decimal Cijena { get; set; }
        public byte[] Slika { get; set; }
        public byte[] SlikaThumb { get; set; }
        public bool Status { get; set; }
        public int GodinaIzdavanja { get; set; }
        public string Opis { get; set; }
        public int ReziserID { get; set; }
    
        public virtual Reziseri Reziseri { get; set; }
        public virtual ICollection<ProizvodiGlumci> ProizvodiGlumcis { get; set; }
        public virtual ICollection<ProizvodiKategorije> ProizvodiKategorijes { get; set; }
    }
}
