//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace movies_service.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reziseri
    {
        public Reziseri()
        {
            this.Proizvodis = new HashSet<Proizvodi>();
        }
    
        public int ReziserID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string DatumRodjenja { get; set; }
        public string Bio { get; set; }
    
        public virtual ICollection<Proizvodi> Proizvodis { get; set; }
    }
}
